export const SELECT_CLIENT = 'SELECT_CLIENT';
export const FILTER_CLIENTS = 'FILTER_CLIENTS'; 
export const LOAD_ALL_CLIENTS_START = 'LOAD_ALL_CLIENTS_START';
export const LOAD_ALL_CLIENTS_SUCCESS = 'LOAD_ALL_CLIENTS_SUCCESS';
export const LOAD_ALL_CLIENTS_FAIL = 'LOAD_ALL_CLIENTS_FAIL';